version: '3.8'

services:
  web:
    build: .
    container_name: online_exam_proctoring
    ports:
      - "5000:5000"  # Expose port 5000 of the container to port 5000 of the host
    volumes:
      - .:/app  # Mount the current directory to the /app directory inside the container
    environment:
      - FLASK_ENV=development  # Set Flask to run in development mode
    restart: unless-stopped  # Restart the container unless it is explicitly stopped
